### ISSUE TITLE
Beagleplay: BQ32000: No driver support for irq or wake_irq

### ISSUE THREAD

**Issue by nmenon** [beagleboard/arm64-mainline-linux#1]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/rtc/rtc-bq32k.c

Does'nt request for wake_irq OR irqs for that matter.

So, though we do describe IRQ capability on the dts, the driver actually never uses it -> preventing alarm ops and wakeup from deepsleep capabilities.

**Comment by sukrutb** [comment]
I can check this one.

**Comment by sukrutb** [comment]
@nmenon @RobertCNelson, seems like bq32000 RTC (https://www.ti.com/lit/ds/symlink/bq32000.pdf) doesn't support the alarm wake-up feature.
So looks like alarm wake-up from deep-sleep using rtc-bq32k driver is not feasible.
Please let me know if my understanding is not correct.
irq is connected to always on domain gpio on AM625, but to generate the interrupt from RTC side,  alarm set and alarm wake-up support e.g.
to generate the irq when alarm expires is not available.
We can use RTC's irq line for Frequency test only.

irq logic can be set by configuring CAL_CFG1 register, but it's not useful to wake-up AM625 from deep-sleep.

**Comment by nmenon** [comment]
Going to Close this s/w issue
Documented as h/w issue https://git.beagleboard.org/beagleplay/beagleplay/-/issues/100
